### ISSUE TITLE
Expand Gencode GFF beyond v23 for human (and maybe mouse)

### ISSUE THREAD

**Issue by lcolladotor** [Bioconductor/AnnotationHubData#1]
Hi,

At https://github.com/Bioconductor/Contributions/issues/1191#issuecomment-537605713 I describe some suggested changes to `AnnotationHubData` which would enable it to create `AnnotationHub` entries for several Gencode versions (instead of just `v23`) such as `v31` and properly label the genome version for the GFF files that were lifted over from hg38 (GRCh38) to hg19 (GRCh37).

As I mention in that comment, I could submit these changes as a pull request. I assume that this is the correct repository to do so, though it's not linked to from http://bioconductor.org/packages/release/bioc/html/AnnotationHubData.html. Please let me know if you are interested in the PR.

Best,
Leo

**Comment by lshep** [comment]
PR always welcome and probably easier for me to review than the github post so I can map the changes in the actual code. Thanks

**Comment by lcolladotor** [comment]
Here you go Lori =)

Best,
Leo
